title: Akshat Chaudhary
description: My Personal Webpage
url: "https://ac031203.github.io"

minimal_mistakes_skin: default
remote_theme: mmistakes/minimal-mistakes
sass:
  sass_dir: _sass
author:
  avatar: /assets/images/profile.jpg
  bio: "Math Geek"
  location: "New Delhi, India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ac031203"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/akshat-chaudhary-13b038223/"

navigation:
  - text: "Home"
    url: /
  - text: "About"
    url: /about/
  - text: "Blog"
    url: /blog/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

comments:
  provider: "utterances"
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

paginate: 5
paginate_path: /blog/page:num/