name: Update View and Like Count

on:
  repository_dispatch:
    types: [update-views, update-likes]

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current count
        id: get_count
        run: |
          ISSUE_NUMBER=${{ github.event.client_payload.issue }}
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
          CURRENT_BODY=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN_1 }}" $API_URL | jq -r '.body')
          COUNT=$(echo "$CURRENT_BODY" | grep -o '[0-9]\+' | head -n 1)
          if [[ -z "$COUNT" ]]; then COUNT=0; fi
          NEW_COUNT=$((COUNT + 1))
          echo "NEW_COUNT=$NEW_COUNT" >> $GITHUB_ENV

      - name: Update issue with new count
        run: |
          ISSUE_NUMBER=${{ github.event.client_payload.issue }}
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
          curl -X PATCH -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN_1 }}" \
               -H "Accept: application/vnd.github.v3+json" \
               $API_URL \
               -d "{\"body\": \"$NEW_COUNT\"}"
